GET  http://localhost:5022/ HTTP/1.1
### 
GET  http://localhost:5022/books HTTP/1.1
### 
GET  http://localhost:5022/books/41 HTTP/1.1
###
GET  http://localhost:5022/books/2/10 HTTP/1.1
###
GET  http://localhost:5022/books/search?Author=Martin&maxPrice=50.00 HTTP/1.1
###
POST  http://localhost:5022/books/10/borrow HTTP/1.1
Content-Type: application/json

{

}
###
POST  http://localhost:5022/books/10/return HTTP/1.1
Content-Type: application/json

{

}
### 
POST  http://localhost:5022/books HTTP/1.1
Content-Type: application/json

{
    "name": "GUI In A Nutshell",
    "author": "Alex Hurmoz",
    "price": 175.99,
    "isAvailable": true
}
### 
PUT  http://localhost:5022/books/41 HTTP/1.1
Content-Type: application/json

{                          
    "name": "Ruby",
    "author": "###",
    "price": 450.50,
    "isAvailable": "true"
}
### 
DELETE  http://localhost:5022/books/42 HTTP/1.1
###
GET http://localhost:5022/Users/12 HTTP/1.1
###
POST  http://localhost:5022/Users HTTP/1.1
Content-Type: application/json

{
    "role": 2,
}
###
DELETE  http://localhost:5022/Users/3 HTTP/1.1
###
PUT  http://localhost:5022/Users HTTP/1.1
Content-Type: application/json

{
    "Role": 1
}
###
GET http://localhost:5022/User/10/Books/ HTTP/1.1